apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: servicemonitor
    app.kubernetes.io/instance: controller-manager-metrics-monitor
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: agent-kube-operator
    app.kubernetes.io/part-of: agent-kube-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090