
FROM alpine:3.19
RUN apk add --no-cache \
    curl \
    bash \
    ca-certificates

ENV KUBECTL_VERSION="v1.28.4"
RUN curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/
RUN mkdir -p /root/.kube
WORKDIR /k8s
CMD ["bash"]