apiVersion: core.agentkube.com/v1alpha1
kind: ResponseProtocol
metadata:
  labels:
    app.kubernetes.io/name: responseprotocol
    app.kubernetes.io/instance: responseprotocol-sample
    app.kubernetes.io/part-of: agent-kube-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: agent-kube-operator
  name: responseprotocol-sample
spec:
  # TODO(user): Add fields here
